// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL5jPlhXOLUsnDt9XZxfCJ_myJbm1yBsk',
    appId: '1:466866919080:web:b20c2706579b440bd6949d',
    messagingSenderId: '466866919080',
    projectId: 'flutter-ai-playground-3dd6e',
    authDomain: 'flutter-ai-playground-3dd6e.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-3dd6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CH0-zyK4UBXcrobrwLBkPe6rnd8istk',
    appId: '1:466866919080:android:53a172796ab7a433d6949d',
    messagingSenderId: '466866919080',
    projectId: 'flutter-ai-playground-3dd6e',
    storageBucket: 'flutter-ai-playground-3dd6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfinpxhe32ScCNnIrrEoM8y0WHrkk8njY',
    appId: '1:466866919080:ios:81e0d89aab906b12d6949d',
    messagingSenderId: '466866919080',
    projectId: 'flutter-ai-playground-3dd6e',
    storageBucket: 'flutter-ai-playground-3dd6e.firebasestorage.app',
    iosBundleId: 'com.smartmart.smartmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfinpxhe32ScCNnIrrEoM8y0WHrkk8njY',
    appId: '1:466866919080:ios:81e0d89aab906b12d6949d',
    messagingSenderId: '466866919080',
    projectId: 'flutter-ai-playground-3dd6e',
    storageBucket: 'flutter-ai-playground-3dd6e.firebasestorage.app',
    iosBundleId: 'com.smartmart.smartmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL5jPlhXOLUsnDt9XZxfCJ_myJbm1yBsk',
    appId: '1:466866919080:web:df31dc127c334b68d6949d',
    messagingSenderId: '466866919080',
    projectId: 'flutter-ai-playground-3dd6e',
    authDomain: 'flutter-ai-playground-3dd6e.firebaseapp.com',
    storageBucket: 'flutter-ai-playground-3dd6e.firebasestorage.app',
  );

}